run0:
	./build/install/app/bin/app -h
run1:
	./build/install/app/bin/app src/test/resources/1.json src/test/resources/2.json

run2:
	./build/install/app/bin/app -f plain src/test/resources/1.json src/test/resources/2.json

run3:
	./build/install/app/bin/app -f json src/test/resources/1.json src/test/resources/2.json

run4:
	./build/install/app/bin/app src/test/resources/1.yml src/test/resources/2.yml

run5:
	./build/install/app/bin/app -f plain src/test/resources/1.yml src/test/resources/2.yml

run6:
	./build/install/app/bin/app -f json src/test/resources/1.yml src/test/resources/2.yml

build:
	./gradlew build

.PHONY: build
