run-dist:
	./build/install/app/bin/app /mnt/c/jva/java-project-71/app/src/test/resources/1.txt /mnt/c/jva/java-project-71/app/src/test/resources/2.txt

build:
	./gradlew clean build

report:
	./gradlew jacocoTestReport

.PHONY: build